<?php
$objItemsListNewsHome = new eventi();$objItemsListNewsHome->_ma_getList('eventi');$objItemsListNewsHome->setOrder('at.DateStart DESC ');if(NEWS_USE_LANGUAGE==1)$objItemsListNewsHome->wObj->setEq('Lang',$lang);$objItemsListNewsHome->wObj->setEq('at.Pub',1);//$objItemsListNewsHome->wObj->setMagg('DateStart',date('Y-m-d'));$objItemsListNewsHome->wObj->setEq('at.FlagHome',1);$objItemsListNewsHome->setLimit( 0,NEWS_MAX_HOME );$objItemsListNewsHome->debug = 0;$objItemsListNewsHome->getData();
$objHPnews = new articoli();$objHPnews->ma_getTopParent('lista');$objHPnewsId=$objHPnews->Data->Id;//  estraggo anche l'id  della pagina  delle  news 
if($objItemsListNewsHome->Data){
    $i=1;	$htmlList='';
	foreach($objItemsListNewsHome->Data as $news){	    $news          = articoli::lang_text_helper($news->Dominio,$news,$lang);	    $dataStart     = invDate::initInvDate($news->DateStart);		$dataStart     = ma_format_date($news->DateStart,'D-M-Y');	    $arr           = explode("-",$news->DateStart);	    $curYearStart  = $arr[0];	    $curMonthStart = (int)$arr[1];
	    $curDayStart   = (int)$arr[2];	    $dataStop      = invDate::initInvDate($news->DateStop);    	$arrStop       = explode("-",$news->DateStop);
	    $curYearStop   = $arrStop[0];	    $curMonthStop  = (int)$arrStop[1];	    $curDayStop    = (int)$arrStop[2];		$dateTitle     = $dataStart;		if($dataStop) {	       $dateTitle.=" - ".ma_format_date($news->DateStop,'D-M-Y');		}        $news->t       = 'lista';
		$itemUrl       = Tool::seoPathHandler($news);		$itemUrl       = Tool::seoPathHandler($objHPnews->Data);		 				$objItemsListNewsHome= new gallery();		$objItemsListNewsHome->makeGallery('immagini'.$objPage->docSuffix,$news->a);		$objItemsListNewsHome->debug=0;		$objItemsListNewsHome->getData();				$active = ( $i == 1) ? "active":"";		//if( ($i % 2) == 1) $htlmPage.="<div class=\"item ".$active."  \" style=\"padding:5px 40px 0px\">\n";					//$htlmPage.="<div class=\"col-md-6 mb15-max-sm\">\n";				$htlmPage.="<div class=\"media\" >\n";					$htlmPage.="<div class=\"media-left hidden\">\n";						$htlmPage.="<a href=\"".$itemUrl."\">\n";						//$htlmPage.=ma_make_image_tt($news->Img,'',$news->Name,'media-object',$tt='&w=195&h=130&zc=1');;						 //$htlmPage.="					<img class=\"media-object\" style="width: 64px; height: 64px;">						$htlmPage.="</a>\n";					$htlmPage.="</div>\n";															$htlmPage.="<div class=\"media-body\">\n";					    $htlmPage.="<a href=\"".$itemUrl."\">\n";							$htlmPage.="<h4 class=\"media-heading pf0 color-main\" id=\"media-heading\">".$news->Name;							//$htlmPage.="<br><span class=\"xx-small color-2\">".$dateTitle."</span>\n";							$htlmPage.="</h4>\n";							$htlmPage.="<p class=\"color-main\">".String::string_limiter(stripslashes($news->Descrizione),NEWS_MAX_WORD_HOME,'...')."</p>\n";						$htlmPage.="</a>\n";					$htlmPage.="</div>\n";							$htlmPage.="</div>\n";			//$htlmPage.="</div><!--/news-->\n";		//if(($i % 2) == 0)$htlmPage.="</div><!--/item-->\n"; 		$i++;	}
}
else { $htlmPage.="<h3>".MSG_NO_ATTIVITA."</h3>";}$htmlListNewsHome = $htlmPage;$htmlList='';