<?phpdefine('MSG_BACK_FOLDER', 'GO TO FOLDER');define('MSG_BACK_SUBFOLDER','GO TO SUBFOLDER');
define('MSG_ITEM_PER_PAGE', 'Items per page');define('MSG_HELP_ADD', 'Add Item');define('MSG_HELP_ADD_CONTACT', 'Add Contact');define('MSG_HELP_INSERISCI_USER','Add  user to this subfolder');define('MSG_HELP_ANNULLA', 'Cancel');define('MSG_HELP_ADDITEM', 'Add new item');define('MSG_HELP_ADDNUOVO','Add new item');
define('MSG_HELP_ADD_USER','Add new user');define('MSG_HELP_ADD_FOLDER','Add new  folder');define('MSG_HELP_ADD_SUBFOLDER','Add new  subfolder');define('MSG_ADD_ALL_USER','Add all  users  to  this subfolders');define('MSG_ADD_ALL_USER_TODOLIST','Add all  users  to  this list');
define('MSG_HELP_EDIT', 'Edit');define('MSG_HELP_CANCEL', 'Delete');define('MSG_HELP_COPY', 'Copy');
define('MSG_HELP_DATASAVED', 'Data has been saved successfully');
define('MSG_HELP_INSERISCI_USER_TODOLIST', 'Add  user');define('MSG_HELP_INSERISCI_TASK_TODOLIST','Add new task');define('MSG_HELP_CLEAR', 'Clear');define('MSG_HELP_CLOSE', 'Close');define('MSG_HELP_CREA_ACCOUNT', 'Create account');define('MSG_HELP_DELETE', 'Delete');define('MSG_HELP_DELETED', 'Item deleted');define('MSG_HELP_DELETE_SELECTED_ITEM', 'Delete  the  selected record');define('MSG_HELP_FIND_GMAPS_POINT','Google Maps Find point');define('MSG_HELP_MODIFY', 'Modify');define('MSG_HELP_OR','or');define('MSG_HELP_SAVE', 'Save');
define('MSG_HELP_GENERATE', 'Genera scadenze');define('MSG_HELP_SAVE_OK', 'Data has been saved successfully');define('MSG_HELP_RESET', 'Reset');define('MSG_HELP_REQUIRED','Required fields');define('MSG_HELP_REGISTER','Registrati');define('MSG_HELP_INSERISCI_EMAIL', 'Inserisci email');define('MSG_HELP_VIEW', 'View');define('MSG_HELP_WARNING','Warning!!!');define('MSG_HELP_WARNING_SUBFOLDER','You\'ll be able to add users to this folder once you\'ve saved it');define('MSG_HELP_WARNING_TODOLIST','You\'ll be able to add users to this list once you\'ve saved it');define('MSG_HELP_UPLOAD','Importa  file');define('MSG_NOITEM', 'No items  found');define('MSG_NO_USER', 'No user  found');define('MSG_NO_DOC', 'No doc found');define('MSG_SELECT', 'Please Select');define('MSG_TORNA_LISTA', 'Back to the list');define('MSG_TORNA_ELENCO','Back to the list');define('MSG_TORNA_AL_CALENDARIO', 'Back to the  calendar');define('MSG_TORNA_AL_DOCUMENTO', 'Back to the doc');define('MSG_TORNA_A_AZIONE', 'Torna all\' azione'); define('MSG_SET_PERMISSION', 'Click to set  file permission');define('MSG_UNSET_PERMISSION', 'Click to unset  file permission');
/***********************************************form  validation and  feedback******************/
define("MSG_FORM_ENTER_YOUR_USERNAME","Type Username");define("MSG_FORM_ENTER_YOUR_PWD","Type password");define('MSG_ERROR_LOGIN', ' Wrong Email or  password <br>please retry');define('MSG_THANK_SUBSCRIBE_NOTIFY','Grazie  per  aver inviato la tua  richiesta');// Label recupero passworddefine('RECOVER_PASSWORD_FORGET', 'Dimenticato la password?');DEFINE('RECOVER_PASSWORD_TEXT','Prego inserire l\'email utilizzato in fase  di registrazione.');DEFINE('RECOVER_PASSWORD_RECOVER','Inviami  la mia password');DEFINE('RECOVER_PASSWORD_RECOVER_EMAIL','Inserisci il tuo email');DEFINE('RECOVER_PASSWORD_BACK','Back');DEFINE('RECOVER_PASSWORD_NOACCOUNT','Sorry, specified email address not found or disabled');DEFINE('RECOVER_PASSWORD_MAIL_FROM',STORE_NAME.' <'.STORE_EMAIL.'>');DEFINE('RECOVER_PASSWORD_MAIL_SUBJ',STORE_NAME.' password recovery');DEFINE('RECOVER_PASSWORD_MAIL_SEND_OK','Your password has been  sent correctly   to  your  email  address');DEFINE('RECOVER_PASSWORD_MAIL_SEND_ERROR','Error during message sending');

/// registrazione dati  utente e attiivazione  utente define('MSG_HELP_EMAIL_NON_PRESENTE','Email not   found');define('MSG_REGISTRATI_PER','Registrati ed effettua il login per iniziare ad usare il servizio');define('MSG_HELP_PWD_INVIATA', 'The new password  has  been  sent  to ypu  email adresss');define('MSG_ERRORE_NOME','Type Name  and  Surname');define('MSG_ERRORE_PWD','Password must be at least 8  chars length');define('MSG_USER_ACCOUNT_ACTIVED','Your account  has  been  active. Now  you can login');define('MSG_USER_ALREADY_ACTIVED','User  already active');

/************************ajax  doc  uploader ***********************/
define('MSG_UPLOAD_AJAX','Drag  your  files  here and  then  press  save');define('MSG_ANTEPRIMA_PDF','Visualizza Pdf');define('MSG_ERROR_UPLOAD_FILE','Error  during file upload or  file  too big');/*errori*/define('MSG_ERROR_EMAIL_NOT_SENT', 'Error sending  email');define('MSG_ERRORE_EMAIL_FORMAT', 'Please type  a  valid email');define('MSG_ERROR_NOME_INVALID','Invalid Name');define('MSG_ERROR_EMAIL_PUT','TypeE-mail');define('MSG_ERROR_EMAIL_PRESENT','E-mail alreday present');define('MSG_ERRORE_EMAIL_NOT_FOUND','Email not  found');define('MSG_ERROR_LOGIN_INVALID','Please  type  username an password');define('MSG_ERROR_LOGIN_NON_ATTIVO','User not active or  without permissio');define('MSG_ERROR_DATE_INALID_FORMAT', 'Invalid date format (YYYY-MM-DD)');
