<?php  $label=array(
    'articoli'=> array(        'delete'=>1,        'archivio'=>'no',        'save'=>1,        'savedata'=>'icon-hdd icon-white,'.MSG_HELP_SAVE.'',        'print'=>0,        'help'=>0,        'copy'=>1,        'add'=>1,        'addlist'=>1,		'preview'=>1,        'list'=>1,        'selbox'=>ma_getParameter('isAdmin'),        'edit'=>1,		'thumb'=>1,		'jsVal'=>'articoli',        'titolo'=>CL_PAGE_TITLE_PAGES,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'searchfileds'=>'1',        'searchMsg'=>'Titolo',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'isbreadCrumbs'=>'1',		'isEditorArea'=>1,		'schede'=>'Main#1,Label#1,Description#1',        'footerbottom'=>'1',     ), 
     'contatti'=> array(
		'delete'=>1,
		'archivio'=>'no',
		'save'=>1,
		'help'=>0,
		'copy'=>1,
		'add'=>1,
        'addlist'=>1,
		'view'=>0,
		'print'=>1,
		'list'=>1,
		'selbox'=>1,
		'edit'=>1,		'thumb'=>1,
		'export'=>1,
		'jsVal'=>'anagraficautenti',
		'titolo'=>CL_PAGE_TITLE_USERS,
		'actiontoolbar'=>'aggiungi',
		'searchToolbar'=>'',
		'layoutEdit'=>'SmallDx',
		'layoutView'=>'Small',
		'isbreadCrumbs'=>'1',
		'isEditorArea'=>0,
        'searchfileds'=>'1',        'searchMsg'=>'Type  Name or Surname'		           	,		 
        'footerbottom'=>'1',
	),		'eventi'=> array(		'delete'=>1,		'archivio'=>'no',		'save'=>1,		'help'=>0,		'copy'=>1,		'add'=>1,        'addlist'=>1,		'view'=>0,		'print'=>1,		'list'=>1,		'selbox'=>1,		'edit'=>1,		'export'=>1,		'jsVal'=>'attivita',		'titolo'=>'Eventi',		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',		'isbreadCrumbs'=>'1',		'isEditorArea'=>1,        'searchfileds'=>'1',        'searchMsg'=>'Titolo',        'footerbottom'=>'1',        'thumb'=>1,	),		'lista'=> array(        'delete'=>1,        'archivio'=>'no',        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>1,        'add'=>1,		'thumb'=>1,		'view'=>0,        'list'=>1,        'edit'=>1,		'export'=>1,		'jsVal'=>'lista',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',		'isbreadCrumbs'=>'1',		'isEditorArea'=>1,        'searchfileds'=>'1',        'searchMsg'=>'Titolo',        'footerbottom'=>'1',        'thumb'=>1,        'selbox'=>ma_getParameter('isAdmin')	),		'folder'=> array(        'delete'=>1,        'archivio'=>'no',        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>0,        'add'=>1,        'addlist'=>1,		'view'=>0,        'list'=>1,        'selbox'=>ma_getParameter('isAdmin'),        'edit'=>1,		'thumb'=>1,		'jsVal'=>'articoli',        'titolo'=>CL_PAGE_TITLE_PAGES,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'isbreadCrumbs'=>'1',		'isEditorArea'=>1,		'schede'=>'Main#1,Label#1,Description#1',        'searchfileds'=>'0',        'footerbottom'=>'1',     ),     'subfolder'=> array(        'delete'=>1,        'archivio'=>'no',        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>0,        'add'=>1,        'addlist'=>1,		'view'=>0,        'list'=>1,        'selbox'=>ma_getParameter('isAdmin'),        'edit'=>1,		'thumb'=>1,		'jsVal'=>'subfolder',        'titolo'=>CL_PAGE_TITLE_PAGES,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'isbreadCrumbs'=>'1',		'isEditorArea'=>1,		'schede'=>'Main#1,Label#1,Description#1',        'searchfileds'=>'0',        'footerbottom'=>'1',     ),
	 'settings'=> array(
		'delete'=>0,
		'archivio'=>'no',
		'save'=>1,
		'help'=>0,
		'copy'=>0,
		'add'=>0,
        'addlist'=>1,
		'view'=>0,
		'print'=>1,
		'list'=>1,
		'selbox'=>1,
		'edit'=>0,
		'export'=>1,
		'jsVal'=>'anagraficautenti',
		'titolo'=>CL_PAGE_TITLE_SETTINGS,
		'actiontoolbar'=>'aggiungi',
		'searchToolbar'=>'',
		'layoutEdit'=>'SmallDx',
		'layoutView'=>'Small',
		'isbreadCrumbs'=>'1',
		'isEditorArea'=>0,
        'searchfileds'=>'0',
        'footerbottom'=>'1',
	),
	 'dominio'=> array(
        'view'=>0,
		'add'=>1,
        'addlist'=>1,
        'delete'=>1,
        'archivio'=>0,		
        'save'=>1,
        'print'=>0,
        'help'=>0,
        'preview'=>0,
        'copy'=>1,
        'selbox'=>1,
         'list'=>1,
        'titolo'=>'',
         'edit'=>1,
         'thumb'=>1,
		'actiontoolbar'=>'aggiungi',
        'searchToolbar'=>'',
        'layoutView'=>'Small',
		'layoutEdit'=>'SmallDx',
        'searchfileds'=>'0',
        'footerbottom'=>'1',
    ),
       'emailmsg'=> array(
        'delete'=>1,
        'archivio'=>'no',
        'save'=>1,
        'print'=>0,
        'help'=>0,
        'copy'=>1,
        'add'=>1,
        'addlist'=>1,
		'view'=>0,
        'list'=>1,
        'selbox'=>ma_getParameter('isAdmin'),
        'edit'=>1,
		'thumb'=>1,
		'jsVal'=>'articoli',
        'titolo'=>CL_PAGE_TITLE_PAGES,
		'actiontoolbar'=>'aggiungi',
		'searchToolbar'=>'',
		'layoutEdit'=>'SmallDx',
		'layoutView'=>'Small',
        'isbreadCrumbs'=>'1',
		'isEditorArea'=>1,
		'schede'=>'Main#1,Label#1,Description#1',
        'searchfileds'=>'0',
        'footerbottom'=>'1',
     ),     'documenti'=> array(        'delete'=>1,        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>0,        'add'=>0,		'thumb'=>0,		'view'=>0,        'list'=>1,		'isEditorArea'=>1,		'jsVal'=>'documenti',		'selbox'=>1,        'edit'=>1,        'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'titolo'=>CL_PAGE_TITLE_DOCUMENTI,		'actiontoolbar'=>'aggiungi,pubblica,exporta',		'searchToolbar'=>'areetematiche,statodocumenti,azioni,attivita,data,regione,tag',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',		'exporta'=>'Id,Area Tematica,Azione,Documento,Titolo,Percorso,Utente,Creato,Ultima Modifica',		     ),     'download'=> array(        		'delete'=>1,        'archivio'=>'no',        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>1,        'add'=>1,        'addlist'=>1,		'thumb'=>1,		'view'=>0,        'list'=>1,		'isEditorArea'=>0,		'jsVal'=>'slogan',		'selbox'=>0,         'edit'=>1,        'titolo'=>CL_PAGE_TITLE_DOWNLOAD,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'searchfileds'=>'0',        'footerbottom'=>'1',		     ),     	  'prodotti'=> array(        		'delete'=>1,        'archivio'=>'no',        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>1,        'add'=>1,        'addlist'=>1,		'thumb'=>1,		'view'=>0,        'list'=>1,		'isEditorArea'=>0,		'jsVal'=>'slogan',		'selbox'=>0,         'edit'=>1,        'titolo'=>CL_PAGE_TITLE_DOWNLOAD,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'searchfileds'=>'0',        'footerbottom'=>'1',		     ),
    'options'=> array(        'delete'=>0,        'archivio'=>'no',        'save'=>1,        'print'=>0,        'help'=>0,        'copy'=>1,        'add'=>1,        'addlist'=>1,		'thumb'=>0,		'view'=>0,        'list'=>1,		'isEditorArea'=>0,		'jsVal'=>'options',		'selbox'=>0,         'edit'=>1,        'titolo'=>CL_PAGE_TITLE_OPTION,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'',		'layoutEdit'=>'SmallDx',		'layoutView'=>'Small',        'searchfileds'=>'0',        'footerbottom'=>'1',     ),     'sitelang'=> array(        'view'=>0,		'add'=>1,        'addlist'=>1,        'delete'=>1,        'archivio'=>0,		        'save'=>1,        'print'=>0,        'help'=>0,        'preview'=>0,        'copy'=>1,        'selbox'=>1,         'list'=>1,        'titolo'=>CL_PAGE_TITLE_SITE_LANG,        'edit'=>1,		'actiontoolbar'=>'aggiungi',        'searchToolbar'=>'01',		'layoutEdit'=>'SmallDx',        'searchfileds'=>'1',        'footerbottom'=>'1',    ),       'social'=> array(        		'delete'  	=> 1,        'archivio'	=> 'no',        'save'		=> 1,        'print'		=> 0,        'help'		=> 0,        'copy'		=> 1,        'add'		=> 1,        'addlist'	=> 1,		'thumb'		=> 1,		'view'		=> 0,        'list'		=> 1,		'isEditorArea'=> 0,		'jsVal'		=> 'slogan',		'selbox'	=> 0,        'edit'		=> 1,        'titolo'	=> CL_PAGE_TITLE_SOCIAL_NETWORK,		'actiontoolbar'=> 'aggiungi',		'searchToolbar'=> '',		'layoutEdit'=> 'SmallDx',		'layoutView'=> 'Small',        'searchfileds'=> '0',        'footerbottom'=> '1',		     ),        	'template'=> array(        'delete'=>1,        'archivio'=>'no',        'save'=>1,        'savedata'=>'icon-hdd icon-white,'.MSG_HELP_SAVE.'',        'print'=>0,        'help'=>0,        'copy'=>1,        'add'=>1,        'addlist'=>1,        'selbox'=>1,        'list'=>1,        'edit'=>1,		'jsVal'=>'template',        'titolo'=>CL_TEMPLATE,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'Dominio,Label,Valore',		'layoutEdit'=>'SmallDx',        'searchfileds'=>'0',        'footerbottom'=>'1',     ),     'user'=> array(        'delete'=>ma_getParameter('isAdmin'),        'archivio'=>'no',        'save'=>1,        'savedata'=>'icon-hdd icon-white,'.MSG_HELP_SAVE.'',        'print'=>0,        'help'=>0,        'copy'=>0,        'add'=>ma_getParameter('isAdmin'),        'addlist'=>1,        'selbox'=>ma_getParameter('isAdmin'),        'list'=>1,        'edit'=>1,        'thumb'=>1,		'jsVal'=>'adminuser',        'titolo'=>CL_PAGE_TITLE_ADMINUSER,		'actiontoolbar'=>'aggiungi',		'searchToolbar'=>'profilo',		'layoutEdit'=>'SmallDx',        'searchfileds'=>'1',        'searchMsg'=>'Type  Name or Surname',        'footerbottom'=>'1',        'selbox'=>ma_getParameter('isAdmin')     ),);
    
    /***********************bottoni*********************/
    $archiveButt	= $label[$Id_sez]['archivio'];
    $editButt		= $label[$Id_sez]['edit'];
	$add			= $label[$Id_sez]['add'];// bottone  per  l'add
    $backbtn		= $label[$Id_sez]['backbtn'];// bottone  js back
	$addButton		= $label[$Id_sez]['addlist'];// bottone  add in list
	$configDoc		= $label[$Id_sez]['configDoc'];// bottone per  creare il  pdf
   
    $footerbottom  	= $label[$Id_sez]['footerbottom'];// footer fixed bottom
	$copyButton    	= $label[$Id_sez]['copy'];
    $listButton   	= $label[$Id_sez]['list'];
	$saveButt		= ($isUser)?'1':$label[$Id_sez]['save'];
    $view			= $label[$Id_sez]['view'];
	$viewModal		= $label[$Id_sez]['viewModal'];
    $selbox			= (ma_get_page()!='home')?$label[$Id_sez]['selbox']:'';
    $delButton		= (ma_get_page()!='home' )?$label[$Id_sez]['delete']:'';
    $printButt		= $label[$Id_sez]['print'];
    $previewButt	= $label[$Id_sez]['preview'];
    $helpButt		= $label[$Id_sez]['help'];
	$xmlButton		= ($isUser)?'0':$label[$Id_sez]['xml'];
	$exportButton	= $label[$Id_sez]['export'];

     /*******************************azioni******************************/    $searchfields	= $label[$Id_sez]['searchfileds'];// bottone  per  abilitare  ricerca    $searchMsg		= ($label[$Id_sez]['searchMsg'])?$label[$Id_sez]['searchMsg']:CL_FIND_PAROLA;// bottone  per  abilitare  ricerca
    $actionToolbar	= explode(',',$label[$Id_sez]['actiontoolbar']);
	$searchToolbar	= explode(',',$label[$Id_sez]['searchToolbar']);
	/***********************************layout****************************/
	
	$layoutEdit		= ($label[$Id_sez]['layoutEdit'])?$label[$Id_sez]['layoutEdit']:'';
	$layoutView		= ($label[$Id_sez]['layoutView'])?$label[$Id_sez]['layoutView']:'';
	/*****************************************abilitazione  thumb*****************/
	$isThumb		= $label[$Id_sez]['thumb'];
	$thumbW			= $label[$Id_sez]['thumbW'];
	$thumbH			= $label[$Id_sez]['thumbH'];
	/******************************************js******************************/
	$jsVal			= (!empty($label[$Id_sez]['jsVal']))?$label[$Id_sez]['jsVal']:$Id_sez;
    	$novalidazione	= $label[$Id_sez]['novalidazione'];	$isEditorArea	= $label[$Id_sez]['isEditorArea'];	$hideDescrizione= ($_SESSION['Permission']=='su')?0:1;

   //array  that  contains  multitable  page
	$multiTable=  array(
	    TABLE_TAG,
        TABLE_CATEGORYTREE_DESCRIZIONI,
		TABLE_DOMINI_DESCRIZIONI,
	);
	$multiUpdate =array(
		TABLE_DOMINI,
        TABLE_CATEGORYTREE,
        TABLE_DOCUMENTI,
		TABLE_ATTIVITA,
		TABLE_MEDIA,
		TABLE_ARTICLE
	);
